[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "tmpc"
version = "0.1.0"
description = "Tube-based Model Predictive Control."
authors = [
    {name = "Rui Huang", email = "ruihuang0421@gmail.com"},
]

dependencies = [
    "cvxpy[glpk]>=1.7.3",
    "matplotlib>=3.10.7",
]

[tool.setuptools.packages.find]
where = ["src"]
